packages:
  - packages/*

catalog:
  '@cloudflare/vite-plugin': ^1.11.0
  '@cloudflare/workers-types': '^4.20250813.0'
  vite: ^7.0.6
  vitest: ^3.2.4
  wrangler: ^4.27.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
