packages:
  - packages/*

catalog:
  '@cloudflare/vite-plugin': ^1.15.2
  '@cloudflare/workers-types': ^4.20251121.0
  vite: ^7.2.4
  vitest: ^4.0.13
  wrangler: ^4.50.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
