packages:
  - packages/*

catalog:
  '@cloudflare/vite-plugin': ^1.12.1
  '@cloudflare/workers-types': ^4.20250830.0
  vite: ^7.1.3
  vitest: ^3.2.4
  wrangler: ^4.33.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
