packages:
  - packages/*

catalog:
  '@cloudflare/vite-plugin': ^1.25.2
  '@cloudflare/workers-types': ^4.20260228.0
  vite: ^7.3.1
  vitest: ^4.0.18
  wrangler: ^4.67.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
