packages:
  - packages/*

catalog:
  '@cloudflare/vite-plugin': ^1.25.6
  '@cloudflare/workers-types': ^4.20260301.1
  vite: ^7.3.1
  vitest: ^4.0.18
  wrangler: ^4.69.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
