import type { TypeDictionary } from './type-checker'
export const fileTypes: TypeDictionary = {
  aac: 'audio',
  aiff: 'audio',
  apng: 'image',
  asf: 'video',
  avi: 'video',
  avif: 'image',
  bmp: 'image',
  dmg: 'file',
  dng: 'image',
  doc: 'document',
  docx: 'document',
  eot: 'file',
  epub: 'document',
  flac: 'audio',
  flv: 'video',
  gif: 'image',
  gifv: 'video',
  heif: 'image',
  icns: 'image',
  ico: 'image',
  jpeg: 'image',
  jpg: 'image',
  m2v: 'video',
  m4a: 'audio',
  m4p: 'audio',
  m4v: 'video',
  md: 'document',
  mdx: 'document',
  mid: 'video',
  mkv: 'video',
  mogg: 'audio',
  mov: 'video',
  mp2: 'audio',
  mp3: 'audio',
  mp4: 'video',
  mpeg: 'video',
  mpg: 'video',
  odt: 'document',
  oga: 'audio',
  ogg: 'video',
  ogv: 'video',
  otf: 'file',
  pdf: 'document',
  png: 'image',
  pptx: 'document',
  psd: 'image',
  qt: 'video',
  rar: 'file',
  rtf: 'document',
  svg: 'image',
  tiff: 'image',
  ttf: 'file',
  txt: 'document',
  vob: 'video',
  wav: 'audio',
  webm: 'video',
  webp: 'image',
  wma: 'audio',
  woff: 'file',
  woff2: 'file',
  xml: 'document',
  zip: 'file',
}

export const siteTypes: TypeDictionary = {
  'amazon.co.uk': 'product',
  'amazon.com': 'product',
  'bandcamp.com': 'audio',
  'bbcgoodfood.com': 'recipe',
  'dai.ly': 'video',
  'dailymotion.com': 'video',
  'deezer.com': 'audio',
  'dev.to': 'article',
  'hopin.com': 'event',
  'imgur.com': 'image',
  'liquor.com': 'recipe',
  'medium.com': 'article',
  'meetup.com': 'event',
  'microsoftstream.com': 'video',
  'mixcloud.com': 'audio',
  'pandora.com': 'audio',
  'soundcloud.com': 'audio',
  'spotify.com': 'audio',
  'tidal.com': 'audio',
  'tiktok.com': 'video',
  'unsplash.com': 'image',
  'vimeo.com': 'video',
  'youtu.be': 'video',
  'youtube.com': 'video',
}

export const types = {
  ...fileTypes,
  ...siteTypes,
}
