CREATE EXTENSION IF NOT EXISTS pgcrypto;--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('active', 'inactive');--> statement-breakpoint
CREATE TYPE "public"."type" AS ENUM('link', 'video', 'audio', 'recipe', 'image', 'document', 'article', 'game', 'book', 'event', 'product', 'note', 'file', 'place');--> statement-breakpoint
CREATE TYPE "public"."feeds_type" AS ENUM('rss', 'api');--> statement-breakpoint
CREATE TYPE "public"."media_rating" AS ENUM('0', '0.5', '1', '1.5', '2', '2.5', '3', '3.5', '4', '4.5', '5');--> statement-breakpoint
CREATE TYPE "public"."media_status" AS ENUM('now', 'skipped', 'done', 'wishlist');--> statement-breakpoint
CREATE TYPE "public"."media_type" AS ENUM('tv', 'film', 'game', 'book', 'podcast', 'music', 'other');--> statement-breakpoint
CREATE TABLE "account" (
	"access_token" text,
	"access_token_expires_at" timestamp with time zone,
	"account_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"id_token" text,
	"password" text,
	"provider_id" text NOT NULL,
	"refresh_token" text,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jwks" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"private_key" text NOT NULL,
	"public_key" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"ip_address" text,
	"token" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_agent" text,
	"user_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"image" text,
	"name" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"created_at" timestamp with time zone DEFAULT now(),
	"expires_at" timestamp with time zone NOT NULL,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"identifier" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bookmark_tags" (
	"bookmark_id" uuid NOT NULL,
	"tag_id" uuid NOT NULL,
	CONSTRAINT "bookmark_tags_pkey" PRIMARY KEY("bookmark_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "bookmarks" (
	"bluesky_post_uri" text,
	"click_count" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
	"description" text,
	"feed" text,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"image" text,
	"modified_at" timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
	"note" text,
	"public" boolean DEFAULT false NOT NULL,
	"star" boolean DEFAULT false NOT NULL,
	"status" "status" DEFAULT 'active' NOT NULL,
	"tags" text[],
	"title" text,
	"tweet" json,
	"type" "type" DEFAULT 'link',
	"url" text,
	"user" uuid
);
--> statement-breakpoint
CREATE TABLE "feeds" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Feeds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"properties" json,
	"type" "feeds_type" NOT NULL,
	"url" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "media" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"image" text,
	"media_id" text,
	"modified_at" timestamp with time zone,
	"name" text DEFAULT '' NOT NULL,
	"platform" text,
	"rating" "media_rating",
	"sort_order" numeric,
	"status" "media_status" DEFAULT 'wishlist',
	"type" "media_type",
	"user" uuid
);
--> statement-breakpoint
CREATE TABLE "oauth_access_token" (
	"client_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"reference_id" text,
	"refresh_id" text,
	"scopes" text[] NOT NULL,
	"session_id" text,
	"token" text NOT NULL,
	"user_id" uuid
);
--> statement-breakpoint
CREATE TABLE "oauth_client" (
	"client_id" text NOT NULL,
	"client_secret" text,
	"contacts" text[],
	"created_at" timestamp with time zone DEFAULT now(),
	"disabled" boolean DEFAULT false,
	"enable_end_session" boolean,
	"grant_types" text[],
	"icon" text,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"metadata" json,
	"name" text,
	"policy" text,
	"post_logout_redirect_uris" text[],
	"public" boolean,
	"redirect_uris" text[] NOT NULL,
	"reference_id" text,
	"require_pkce" boolean,
	"response_types" text[],
	"scopes" text[],
	"skip_consent" boolean,
	"software_id" text,
	"software_statement" text,
	"software_version" text,
	"subject_type" text,
	"token_endpoint_auth_method" text,
	"tos" text,
	"type" text,
	"updated_at" timestamp with time zone DEFAULT now(),
	"uri" text,
	"user_id" uuid
);
--> statement-breakpoint
CREATE TABLE "oauth_consent" (
	"client_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"reference_id" text,
	"scopes" text[] NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"user_id" uuid
);
--> statement-breakpoint
CREATE TABLE "oauth_refresh_token" (
	"auth_time" timestamp with time zone,
	"client_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"id" text PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"reference_id" text,
	"revoked" timestamp with time zone,
	"scopes" text[] NOT NULL,
	"session_id" text,
	"token" text NOT NULL,
	"user_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"api_key" uuid DEFAULT gen_random_uuid() NOT NULL,
	"avatar_url" text,
	"id" uuid PRIMARY KEY NOT NULL,
	"settings_collections_visible" boolean DEFAULT false NOT NULL,
	"settings_group_by_date" boolean DEFAULT false,
	"settings_pinned_tags" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"settings_tags_visible" boolean DEFAULT false NOT NULL,
	"settings_top_tags_count" numeric,
	"settings_types_visible" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone,
	"username" text,
	CONSTRAINT "username_length" CHECK (char_length("profiles"."username") >= 3)
);
--> statement-breakpoint
CREATE TABLE "tags" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tag" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "toots" (
	"created_at" timestamp with time zone DEFAULT now(),
	"db_user_id" uuid,
	"hashtags" text[],
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"liked_toot" boolean DEFAULT false NOT NULL,
	"media" json,
	"reply" json,
	"text" text DEFAULT '',
	"toot_id" text,
	"toot_url" text,
	"urls" json,
	"user_avatar" text,
	"user_id" text,
	"user_name" text
);
--> statement-breakpoint
CREATE TABLE "tweets" (
	"created_at" timestamp with time zone DEFAULT now(),
	"db_user_id" uuid,
	"hashtags" text[],
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"liked_tweet" boolean DEFAULT false NOT NULL,
	"media" json,
	"reply" json,
	"text" text DEFAULT '',
	"tweet_id" text,
	"tweet_url" text,
	"urls" json,
	"user_avatar" text,
	"user_id" text,
	"user_name" text
);
--> statement-breakpoint
CREATE TABLE "user_integrations" (
	"bluesky_app_password" text,
	"bluesky_enabled" boolean DEFAULT false NOT NULL,
	"bluesky_handle" text,
	"bluesky_last_error" text,
	"bluesky_post_prefix" text,
	"bluesky_post_suffix" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"user_id" uuid PRIMARY KEY NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmark_tags" ADD CONSTRAINT "bookmark_tags_bookmark_id_bookmarks_id_fk" FOREIGN KEY ("bookmark_id") REFERENCES "public"."bookmarks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmark_tags" ADD CONSTRAINT "bookmark_tags_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmarks" ADD CONSTRAINT "bookmarks_user_user_id_fk" FOREIGN KEY ("user") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media" ADD CONSTRAINT "media_user_user_id_fk" FOREIGN KEY ("user") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_client_client_id_key" ON "oauth_client" USING btree ("client_id");--> statement-breakpoint
ALTER TABLE "oauth_access_token" ADD CONSTRAINT "oauth_access_token_client_id_oauth_client_client_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."oauth_client"("client_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_access_token" ADD CONSTRAINT "oauth_access_token_refresh_id_oauth_refresh_token_id_fk" FOREIGN KEY ("refresh_id") REFERENCES "public"."oauth_refresh_token"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_access_token" ADD CONSTRAINT "oauth_access_token_session_id_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_access_token" ADD CONSTRAINT "oauth_access_token_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_client" ADD CONSTRAINT "oauth_client_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_consent" ADD CONSTRAINT "oauth_consent_client_id_oauth_client_client_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."oauth_client"("client_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_consent" ADD CONSTRAINT "oauth_consent_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_refresh_token" ADD CONSTRAINT "oauth_refresh_token_client_id_oauth_client_client_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."oauth_client"("client_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_refresh_token" ADD CONSTRAINT "oauth_refresh_token_session_id_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_refresh_token" ADD CONSTRAINT "oauth_refresh_token_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_user_id_fk" FOREIGN KEY ("id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toots" ADD CONSTRAINT "toots_db_user_id_user_id_fk" FOREIGN KEY ("db_user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tweets" ADD CONSTRAINT "tweets_db_user_id_user_id_fk" FOREIGN KEY ("db_user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_integrations" ADD CONSTRAINT "user_integrations_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_token_key" ON "session" USING btree ("token");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "user_email_key" ON "user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "bookmarks_user_idx" ON "bookmarks" USING btree ("user");--> statement-breakpoint
CREATE INDEX "bookmarks_status_idx" ON "bookmarks" USING btree ("status");--> statement-breakpoint
CREATE INDEX "media_user_idx" ON "media" USING btree ("user");--> statement-breakpoint
CREATE UNIQUE INDEX "oauth_access_token_token_key" ON "oauth_access_token" USING btree ("token");--> statement-breakpoint
CREATE INDEX "oauth_access_token_client_id_idx" ON "oauth_access_token" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "oauth_access_token_session_id_idx" ON "oauth_access_token" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "oauth_access_token_user_id_idx" ON "oauth_access_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth_client_user_id_idx" ON "oauth_client" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth_consent_client_id_idx" ON "oauth_consent" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "oauth_consent_user_id_idx" ON "oauth_consent" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth_refresh_token_client_id_idx" ON "oauth_refresh_token" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "oauth_refresh_token_session_id_idx" ON "oauth_refresh_token" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "oauth_refresh_token_user_id_idx" ON "oauth_refresh_token" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_api_key_key" ON "profiles" USING btree ("api_key");--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_username_key" ON "profiles" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX "tags_tag_key" ON "tags" USING btree ("tag");--> statement-breakpoint
CREATE UNIQUE INDEX "toots_toot_id_key" ON "toots" USING btree ("toot_id");--> statement-breakpoint
CREATE INDEX "toots_db_user_id_idx" ON "toots" USING btree ("db_user_id");--> statement-breakpoint
CREATE INDEX "tweets_db_user_id_idx" ON "tweets" USING btree ("db_user_id");