CREATE TYPE "public"."journal_status" AS ENUM('active', 'inactive', 'deleted', 'archived', 'draft');--> statement-breakpoint
CREATE TABLE "journals" (
	"created_at" timestamp with time zone DEFAULT now(),
	"description" text,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "journals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"owner" uuid,
	"status" "journal_status" DEFAULT 'active' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "journal_entries" (
	"created_at" timestamp with time zone DEFAULT now(),
	"date" date,
	"end_date" date,
	"entry" text,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "journal_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"journal" bigint,
	"media" text[],
	"owner" uuid,
	"status" "journal_status" DEFAULT 'active' NOT NULL,
	"time" time
);
--> statement-breakpoint
CREATE TABLE "checklists" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "checklists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"owner" uuid,
	"status" "journal_status" DEFAULT 'active' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "checklist_entries" (
	"checklist_id" bigint NOT NULL,
	"count" bigint,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "checklist_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"journal_entry_id" bigint NOT NULL,
	"note" text,
	"owner" uuid,
	"status" "journal_status" DEFAULT 'active' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "journals" ADD CONSTRAINT "journals_owner_user_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_journal_journals_id_fk" FOREIGN KEY ("journal") REFERENCES "public"."journals"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_owner_user_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklists" ADD CONSTRAINT "checklists_owner_user_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist_entries" ADD CONSTRAINT "checklist_entries_checklist_id_checklists_id_fk" FOREIGN KEY ("checklist_id") REFERENCES "public"."checklists"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist_entries" ADD CONSTRAINT "checklist_entries_journal_entry_id_journal_entries_id_fk" FOREIGN KEY ("journal_entry_id") REFERENCES "public"."journal_entries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checklist_entries" ADD CONSTRAINT "checklist_entries_owner_user_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "journals_owner_idx" ON "journals" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "journal_entries_owner_idx" ON "journal_entries" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "journal_entries_journal_idx" ON "journal_entries" USING btree ("journal");--> statement-breakpoint
CREATE INDEX "checklists_owner_idx" ON "checklists" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "checklist_entries_checklist_id_idx" ON "checklist_entries" USING btree ("checklist_id");--> statement-breakpoint
CREATE INDEX "checklist_entries_journal_entry_id_idx" ON "checklist_entries" USING btree ("journal_entry_id");
