/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: ['media'],
  plugins: [require('tailwindcss-animate')],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
        bp1: '500px',
        bp2: '768px',
        bp3: '1024px',
      },
    },
    extend: {
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      borderRadius: {
        l: 'var(--radii-l)',
        m: 'var(--radii-m)',
        s: 'var(--radii-s) !important',
        xl: 'var(--radii-xl)',
      },
      colors: {
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        accent1: 'var(--accent1)',
        accent2: 'var(--accent2)',
        accent3: 'var(--accent3)',
        accent4: 'var(--accent4)',
        accent5: 'var(--accent5)',
        accent6: 'var(--accent6)',
        accent7: 'var(--accent7)',
        accent8: 'var(--accent8)',
        accent9: 'var(--accent9)',
        accent10: 'var(--accent10)',
        accent11: 'var(--accent12)',
        accent12: 'var(--accent11)',
        background: 'var(--background)',
        border: 'var(--border)',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        foreground: 'var(--foreground)',
        input: 'hsl(var(--input))',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        ring: 'hsl(var(--ring))',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        theme1: 'var(--theme1)',
        theme2: 'var(--theme2)',
        theme3: 'var(--theme3)',
        theme4: 'var(--theme4)',
        theme5: 'var(--theme5)',
        theme6: 'var(--theme6)',
        theme7: 'var(--theme7)',
        theme8: 'var(--theme8)',
        theme9: 'var(--theme9)',
        theme10: 'var(--theme10)',
        theme11: 'var(--theme12)',
        theme12: 'var(--theme11)',
      },
      fontSize: {
        base: 'var(--step-0)',
        'step--1': 'var(--step--1)',
        'step--2': 'var(--step--2)',
        'step--3': 'var(--step--3)',
        'step-0': 'var(--step-0)',
        'step-1': 'var(--step-1)',
        'step-2': 'var(--step-2)',
        'step-3': 'var(--step-3)',
        'step-4': 'var(--step-4)',
        'step-5': 'var(--step-5)',
        'step-6': 'var(--step-6)',
        'step-7': 'var(--step-7)',
        'step-8': 'var(--step-8)',
        'step-9': 'var(--step-9)',
        'step-10': 'var(--step-10)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      spacing: {
        '2xl': 'var(--space-2xl)',
        '2xs': 'var(--space-2xs)',
        '3xl': 'var(--space-3xl)',
        '3xs': 'var(--space-3xs)',
        '4xs': 'var(--space-4xs)',
        l: 'var(--space-l)',
        m: 'var(--space-m)',
        s: 'var(--space-s)',
        xl: 'var(--space-xl)',
        xs: 'var(--space-xs)',
      },
    },
  },
}
