export type LinkType =
  | 'link'
  | 'video'
  | 'audio'
  | 'recipe'
  | 'image'
  | 'document'
  | 'article'
  | 'game'
  | 'book'
  | 'event'
  | 'product'
  | 'note'
  | 'file'

export type TypeDictionary = Record<string, LinkType>

export const fileTypes: TypeDictionary = {
  aac: 'audio',
  aiff: 'audio',
  apng: 'image',
  asf: 'video',
  avi: 'video',
  avif: 'image',
  bmp: 'image',
  dmg: 'file',
  dng: 'image',
  doc: 'document',
  docx: 'document',
  eot: 'file',
  epub: 'document',
  flac: 'audio',
  flv: 'video',
  gif: 'image',
  gifv: 'video',
  heif: 'image',
  icns: 'image',
  ico: 'image',
  jpeg: 'image',
  jpg: 'image',
  m2v: 'video',
  m4a: 'audio',
  m4p: 'audio',
  m4v: 'video',
  md: 'document',
  mdx: 'document',
  mid: 'video',
  mkv: 'video',
  mogg: 'audio',
  mov: 'video',
  mp2: 'audio',
  mp3: 'audio',
  mp4: 'video',
  mpeg: 'video',
  mpg: 'video',
  odt: 'document',
  oga: 'audio',
  ogg: 'video',
  ogv: 'video',
  otf: 'file',
  pdf: 'document',
  png: 'image',
  pptx: 'document',
  psd: 'image',
  qt: 'video',
  rar: 'file',
  rtf: 'document',
  svg: 'image',
  tiff: 'image',
  ttf: 'file',
  txt: 'document',
  vob: 'video',
  wav: 'audio',
  webm: 'video',
  webp: 'image',
  wma: 'audio',
  woff: 'file',
  woff2: 'file',
  xml: 'document',
  zip: 'file',
}

export const siteTypes: TypeDictionary = {
  'allrecipes.com': 'recipe',
  'amazon.co.uk': 'product',
  'amazon.com': 'product',
  'amzn.to': 'product',
  'arxiv.org': 'document',
  'bandcamp.com': 'audio',
  'bbcgoodfood.com': 'recipe',
  'dai.ly': 'video',
  'dailymotion.com': 'video',
  'deezer.com': 'audio',
  'dev.to': 'article',
  'developer.mozilla.org': 'document',
  'docs.google.com': 'document',
  'drive.google.com': 'document',
  'dropbox.com': 'document',
  'ebay.com': 'product',
  'etsy.com': 'product',
  'eventbrite.com': 'event',
  'flickr.com': 'image',
  'foodnetwork.com': 'recipe',
  'giphy.com': 'image',
  'gitbook.io': 'document',
  'hashnode.com': 'article',
  'hopin.com': 'event',
  'imgur.com': 'image',
  'liquor.com': 'recipe',
  'loom.com': 'video',
  'lu.ma': 'event',
  'medium.com': 'article',
  'meetup.com': 'event',
  'microsoftstream.com': 'video',
  'mixcloud.com': 'audio',
  'music.apple.com': 'audio',
  'notion.so': 'document',
  'onedrive.live.com': 'document',
  'pandora.com': 'audio',
  'podcasts.apple.com': 'audio',
  'readthedocs.io': 'document',
  'researchgate.net': 'document',
  'rumble.com': 'video',
  'sharepoint.com': 'document',
  'slideshare.net': 'document',
  'soundcloud.com': 'audio',
  'spotify.com': 'audio',
  'substack.com': 'article',
  'tidal.com': 'audio',
  'tiktok.com': 'video',
  'twitch.tv': 'video',
  'unsplash.com': 'image',
  'v.redd.it': 'video',
  'vimeo.com': 'video',
  'w3.org': 'document',
  'youtu.be': 'video',
  'youtube.com': 'video',
  'zenodo.org': 'document',
}

export const types: TypeDictionary = {
  ...fileTypes,
  ...siteTypes,
}
